services:
  nginx:
    image: ghcr.io/vinaysheelsagar/vinaysheelsagar.com-nginx:latest
    ports:
      - "80:80"
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - nginx-net

# ghcr.io/vinaysheelsagar/vinaysheelsagar.com-nginx
  frontend:
    image: ghcr.io/vinaysheelsagar/vinaysheelsagar.com-frontend:latest
    ports:
      - "5173:5173"
    # volumes:
    #   - ./app:/app
    #   - /app/node_modules
    #   - /app/.vscode
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    deploy:
      replicas: 2
    networks:
      - nginx-net


networks:
  nginx-net:
    driver: overlay