services:
  nginx:
    image: nginx
    ports: 
      - "80:80"
    volumes:
      - ./config:/etc/nginx:ro
    # networks:
    #   - nginx-net
    deploy:
      placement:
        constraints:
          - node.role == manager