name: Release Build & Deploy

on:
    release: 
        types: [published]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        
        permissions: 
            contents: read
            packages: write
        
        steps:
            - name: Checkout code
              uses: action/checkout@v3
            
            - name: Log in to GHCR
              run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Build docker image with release tag
              run: |
                docker build -t ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }} .
                docker tag ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }} ghcr.io/${{ github.repository }}:latest
            
            - name: Pushing image to GHCR
              run: |
                docker push ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
                docker push ghcr.io/${{ github.repository }}:latest
            
            - name: Trigger deploy to server
              run: |
                curl -X POST ${{ secrets.DEPLOY_HOOK }}